[project]
name = "Integrate"
version = "0.1.0"
description = "The first test package"
dependencies = [
    "flask",
    "click"
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"