[project]
name = "Hennessy_Integrate"
version = "0.1.0"
description = "The first test package"
dependencies = [
    "flask",
    "click",
]

[build-system]
requires = ["setuptools >= 75.3.2"]
build-backend = "setuptools.build_meta"
